name: CI/CD Pipeline for Real-Time Chat App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set Git Identity
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub CI"

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./Server

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./client

      - name: Run Backend Tests
        run: npm test
        working-directory: ./Server

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./client
